### ISSUE TITLE
Text löschen geht nicht

### ISSUE THREAD

**Issue by eikooo** [vcpbzol/hajk2go-webmanager#1]
Wenn man versucht einen Text zu löschen (=leeren Text speichern) kommt die Fehlermeldung "Falsche Daten. Du hast falsch formatierte Daten in die Felder eingetragen. Formular zurückgesetzt."

**Comment by jannis2711** [comment]
läuft jetzt, nun sind auch leere Angaben möglich.
Das Textelement wird nicht gelöscht, nur geleert. Die Verküpfung in der Relationstabelle wird nicht gelöscht.
