### ISSUE TITLE
Anzeige für App-Feedback

### ISSUE THREAD

**Issue by eikooo** [vcpbzol/hajk2go-webmanager#6]
Eine Ansicht für das Feedback ohne Hajkbezug bauen. Im Moment wird das App-Feedback mit HajkId = 0 und PostId = 0 in die Datenbank geschrieben.

**Comment by jannis2711** [comment]
![image](https://user-images.githubusercontent.com/62658879/137638755-3e8d3842-4e1c-481c-9d62-79fcea520cce.png)

https://webmanager.hajk2go.de/viewFeedback.php
