### ISSUE TITLE
Hajk-Feedback wird nicht angezeigt

### ISSUE THREAD

**Issue by eikooo** [vcpbzol/hajk2go-webmanager#8]
Feedback einträge für einen Hajk (ohne Postenbezug, PostenID = 0) werden nicht angezeigt.

**Comment by jannis2711** [comment]
Es gibt nun Hajkfeedback, Postenfeedback getrennt in der Übersicht, siehe Screenshot.
![image](https://user-images.githubusercontent.com/62658879/137639984-666061cb-53ec-473c-af07-cffcd31eddbf.png)
